# Use root/example as user/password credentials
version: '3.6'

services:
  mysqlticket:
    container_name: mysqlticket
    ports: 
        - "3306:3306"
    image: mysql:5.6.43
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
    - /var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=TicketValidationDb
    - MYSQL_USER=TicketValidation
    - MYSQL_PASSWORD=TicketValidation